name: Deploy solution to TEST and PROD
# Triggered automatically when changes are merged to main, or manually.

on:
  push:
    branches:
      - main
    paths:
      - "solutions/**"
      - "deploymentSettings/**"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
jobs:
  Release-solution:
    uses: ./.github/workflows/release-solution-to-prod.yml
    with:
      solution_name: ManufakturaOrdersFlowsSharepoint
      TEST_ENVIRONMENT_URL: https://manufaktura-test.crm11.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://manufaktura.crm11.dynamics.com/
      CLIENT_ID: 6a478448-0380-4a07-8b3f-aa5a3ce468db
      TENANT_ID: 9096fb11-ab2c-4e04-b90c-dc3ce88d59fb
      APPROVERS: mbochenko
      MINIMUM_APPROVALS: 1
      TEST_DEPLOYMENT_SETTINGS: deploymentSettings/test.json
      PROD_DEPLOYMENT_SETTINGS: deploymentSettings/prod.json
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
